spring:
  application:
    name: shop-backend
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${MYSQL_HOST}/shop?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  flyway:
    enabled: true
    out-of-order: true
    encoding: UTF-8
    url: jdbc:mysql://${MYSQL_HOST}
    schemas: shop
    user: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
