server:
  port: 9001
  servlet:
    context-path: /api

spring:
  profiles:
    default: dev
  application:
    name: backend

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

